=== davispuh/Source-Code/Languages/XSD.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://github.com/davispuh/Source-Code"
  xmlns="https://github.com/davispuh/Source-Code">

  <xs:element name="world">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="country" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="country">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="city" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="CountryName" use="required" />
      <xs:attribute name="code" type="CountryCode" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="city">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="land" />
        <xs:element ref="population" />
        <xs:group ref="people" />
      </xs:sequence>
      <xs:attribute name="id" type="xs:positiveInteger" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="name" type="xs:string" />
  <xs:element name="land" type="xs:decimal" />
  <xs:element name="population" type="xs:nonNegativeInteger" />

  <xs:group name="people">
    <xs:sequence>
      <xs:element name="artists" type="count" />
      <xs:element name="musicians" type="count" />
    </xs:sequence>
  </xs:group>

  <xs:simpleType name="CountryName">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Russia" />
      <xs:enumeration value="Canada" />
      <xs:enumeration value="United States" />
      <xs:enumeration value="Australia" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CountryCode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RU" />
      <xs:enumeration value="CA" />
      <xs:enumeration value="US" />
      <xs:enumeration value="AU" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="count">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:minInclusive value="0" />
      <xs:maxExclusive value="10000000" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== davispuh/Source-Code/Languages/XML.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="XSL.xsl"?>
<world xmlns="https://github.com/davispuh/Source-Code" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="XSD.xsd">
  <!--
    XML is good ;)
  -->
  <country name="Russia" code="RU"></country>
  <country name="Canada" code="CA"></country>
  <country name="United States" code="US">
    <city id="1">
      <name>Los Angeles</name>
      <land>1213.850</land>
      <population>3792621</population>
      <artists>303096</artists>
      <musicians>364120</musicians>
    </city>
    <city id="2">
      <name>New York</name>
      <land>783.842</land>
      <population>8175133</population>
      <artists>368723</artists>
      <musicians>382600</musicians>
    </city>
    <city id="3">
      <name>Chicago</name>
      <land>589.571</land>
      <population>2695598</population>
      <artists>350170</artists>
      <musicians>145569</musicians>
    </city>
  </country>
  <country name="Australia" code="AU"></country>
</world>
